### PR TITLE
Change "alphabet" to "characterSet"

### PR DESCRIPTION
**Pull request by aburchell**
Generalize the word used to specify the set of possible responses.

### CODE REVIEW

**Comment by aburchell** [comment]
After this I think I should also do the change for "label" to "block_condition", which I also did with Denis and have mixed into the bounding refactoring.

**Comment by denispelli** [comment]
Great!  Thx

On Tue, Dec 28, 2021 at 5:50 PM Gus Burchell ***@***.***>
wrote:

> After this I think I should also do the change for "label" to
> "block_condition", which I also did with Denis and have mixed into the
> bounding refactoring.
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_EasyEyes_threshold_pull_45-23issuecomment-2D1002311231&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=7X-NKAXavKeKD9gIvst_RX6MqmtP6wERm4LVB5ZkcI4&m=S97JzVXMVpJJQyvzeIE6aO9vanjygraosKBgS0X7WhSjPzpy9hfEYEKGB1_qFe1r&s=DYncxYm0y4sxXSLzr2e1Mz7ORR3mvD1gIS2jpTgTk5s&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADKWX6ZLB2JNXZZ242DSQUTUTI5JTANCNFSM5K44U4CQ&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=7X-NKAXavKeKD9gIvst_RX6MqmtP6wERm4LVB5ZkcI4&m=S97JzVXMVpJJQyvzeIE6aO9vanjygraosKBgS0X7WhSjPzpy9hfEYEKGB1_qFe1r&s=uAQn6v8rsW-8GAu4M3gyedpJoYe3fd_M5bt5mdrpOAw&e=>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=7X-NKAXavKeKD9gIvst_RX6MqmtP6wERm4LVB5ZkcI4&m=S97JzVXMVpJJQyvzeIE6aO9vanjygraosKBgS0X7WhSjPzpy9hfEYEKGB1_qFe1r&s=Rf2Y5wlouZDvjv4UE9AVD9pxAP39A_8l7cuTFg8EYss&e=>
> or Android
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=7X-NKAXavKeKD9gIvst_RX6MqmtP6wERm4LVB5ZkcI4&m=S97JzVXMVpJJQyvzeIE6aO9vanjygraosKBgS0X7WhSjPzpy9hfEYEKGB1_qFe1r&s=153WTPHsYR0RcKDOof2ddiMbYfWXI55OLhnr5DOaFy8&e=>.
>
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>
-- 

Denis Pelli
Professor of Psychology & Neural Science, New York University
+1-646-258-7524  | ***@***.***
http://psych.nyu.edu/pelli/  | Skype: denispelli
| http://denispelli.com

Sent from my iphone.

**Comment by aburchell** [comment]
@peilingjiang The Netlify checks are still breaking here. Did we expect that? Should I merge the PR?

**Comment by peilingjiang** [comment]
The log still says `targetAlphabet` is not recognized. I think it should just be cache this time.

**Comment by aburchell** [comment]
Also possible I missed a mention somewhere. I'll check again.

**Comment by aburchell** [comment]
@peilingjiang I didn't find anything amiss. Should I try merging the PR?

**Comment by peilingjiang** [comment]
Can you try running `npm run examples` locally? If you didn't get any errors then it should be fine.

**Comment by aburchell** [comment]
Good suggestion. That pointed out the offending mention to `targetAlphabet` was in `examples/tables/demoExperiment.xlsx`. Apparently Excel files aren't penetrable to VSCode's Find In Files functionality, tsk tsk. Checks seem good now.

**Pull request merged**
